// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcEkJa5ae1HcStB3_hrEBDMX3a_Voh_GI',
    appId: '1:161428670516:web:4570e96841652955702261',
    messagingSenderId: '161428670516',
    projectId: 'chat-flutter-28f00',
    authDomain: 'chat-flutter-28f00.firebaseapp.com',
    storageBucket: 'chat-flutter-28f00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgf03felHJkhscKAEM0xDO7xuUN9Hpz3A',
    appId: '1:161428670516:android:5cac328afc44489e702261',
    messagingSenderId: '161428670516',
    projectId: 'chat-flutter-28f00',
    storageBucket: 'chat-flutter-28f00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj3m3noLgsOLkPywdVUEuZ9yXmWSCWXq0',
    appId: '1:161428670516:ios:8c2d2c7030814ea8702261',
    messagingSenderId: '161428670516',
    projectId: 'chat-flutter-28f00',
    storageBucket: 'chat-flutter-28f00.appspot.com',
    iosClientId: '161428670516-kdcl1hg2r9ntfo0mupghi2ajn6mvgjej.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj3m3noLgsOLkPywdVUEuZ9yXmWSCWXq0',
    appId: '1:161428670516:ios:4eb896c29f257bd0702261',
    messagingSenderId: '161428670516',
    projectId: 'chat-flutter-28f00',
    storageBucket: 'chat-flutter-28f00.appspot.com',
    iosClientId: '161428670516-q6c3ehq7sijtq0gik1gaja3av6fnbg4i.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatFirebase.RunnerTests',
  );
}
